name: flutter_projetopedromafra
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  easy_splash_screen: ^1.0.4
  flutter:
    sdk: flutter
  device_preview: ^1.1.0
  mapbox_gl: ^0.16.0
  geolocator: ^9.0.2
  geocoding : ^2.0.0
  flutter_mapbox_autocomplete: ^2.0.0
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.1
  firebase_auth: ^4.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - lib/images/
