// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn8YNoyW4I1CgWmH67oY-x5iYkZ_NnjkE',
    appId: '1:81913042520:web:5c9c8116f7ed0f19d45c2d',
    messagingSenderId: '81913042520',
    projectId: 'fecamsp-a8469',
    authDomain: 'fecamsp-a8469.firebaseapp.com',
    storageBucket: 'fecamsp-a8469.appspot.com',
    measurementId: 'G-NLYVGX8DT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtjGcQ3gxO39po0kz9Qzm5FEw_cqiVXBM',
    appId: '1:81913042520:android:af386b962c8bdc31d45c2d',
    messagingSenderId: '81913042520',
    projectId: 'fecamsp-a8469',
    storageBucket: 'fecamsp-a8469.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCONYnkXgsbdJy6yS_EatqJ-6sN0ftPIx4',
    appId: '1:81913042520:ios:4df53269a4e2ae97d45c2d',
    messagingSenderId: '81913042520',
    projectId: 'fecamsp-a8469',
    storageBucket: 'fecamsp-a8469.appspot.com',
    iosBundleId: 'com.example.flutterProjetopedromafra',
  );
}
